version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      abaplint:
        patterns:
          - "@abaplint/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      
